services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/entry
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASS}
      - EMBED_SERVICE_HOST=inference
    depends_on:
      - redis
      - postgres
      - inference
    ports:
      - 8080:8080

  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    ports:
      - ${INFERENCE_PORT}:50051
    env_file:
      - .env

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=entry
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis/redis-stack:latest
    labels:
      - org.springframework.boot.service-connection=redis
    ports:
      - ${REDIS_PORT}:6379